// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsNWRR2ssLIna3ia49LPMahouRrOOlj0w',
    appId: '1:537878678420:android:00680200806129d0f3dd81',
    messagingSenderId: '537878678420',
    projectId: 'conexao-firebase-fd12d',
    databaseURL: 'https://conexao-firebase-fd12d-default-rtdb.firebaseio.com',
    storageBucket: 'conexao-firebase-fd12d.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhLeAPYUWpH-_-VnytPK8naHF46S60GEM',
    appId: '1:537878678420:web:8139f0ec9cd0986ff3dd81',
    messagingSenderId: '537878678420',
    projectId: 'conexao-firebase-fd12d',
    authDomain: 'conexao-firebase-fd12d.firebaseapp.com',
    databaseURL: 'https://conexao-firebase-fd12d-default-rtdb.firebaseio.com',
    storageBucket: 'conexao-firebase-fd12d.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClMFPMjN056sPPC2LJkCRULEUGR4CkeOw',
    appId: '1:537878678420:ios:75934b45a384bfbff3dd81',
    messagingSenderId: '537878678420',
    projectId: 'conexao-firebase-fd12d',
    databaseURL: 'https://conexao-firebase-fd12d-default-rtdb.firebaseio.com',
    storageBucket: 'conexao-firebase-fd12d.firebasestorage.app',
    iosBundleId: 'com.example.flutterQuizApp',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClMFPMjN056sPPC2LJkCRULEUGR4CkeOw',
    appId: '1:537878678420:ios:75934b45a384bfbff3dd81',
    messagingSenderId: '537878678420',
    projectId: 'conexao-firebase-fd12d',
    databaseURL: 'https://conexao-firebase-fd12d-default-rtdb.firebaseio.com',
    storageBucket: 'conexao-firebase-fd12d.firebasestorage.app',
    iosBundleId: 'com.example.flutterQuizApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBhLeAPYUWpH-_-VnytPK8naHF46S60GEM',
    appId: '1:537878678420:web:36caacc33dc41e7ef3dd81',
    messagingSenderId: '537878678420',
    projectId: 'conexao-firebase-fd12d',
    authDomain: 'conexao-firebase-fd12d.firebaseapp.com',
    databaseURL: 'https://conexao-firebase-fd12d-default-rtdb.firebaseio.com',
    storageBucket: 'conexao-firebase-fd12d.firebasestorage.app',
  );
}
